services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  openmrs:
    environment:
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
