sonar.organization=bami-flogert
sonar.projectKey=bami-flogert_openmrs-module-htmlformentry
sonar.host.url=https://sonarcloud.io

# Maven multi-module: geen handmatige sonar.sources (plugin detecteert modules uit pom.xml)
sonar.exclusions=.github/**,**/target/**,**/*.min.js
sonar.coverage.jacoco.xmlReportPaths=omod/target/site/jacoco/jacoco.xml
